# Generated by Django 3.2.20 on 2025-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mayorista_tipo',
            field=models.IntegerField(choices=[(0, 'Cliente Normal'), (1, 'Mayorista 1'), (2, 'Mayorista 2'), (3, 'Mayorista 3')], default=0),
        ),
    ]
