# Generated by Django 4.2.20 on 2025-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20250315_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='faltas_agresivas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
