# Generated by Django 4.2.20 on 2025-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_faltas_agresivas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='faltas_agresivas',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='mayorista_tipo',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
