# Generated by Django 4.2.20 on 2025-07-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(help_text='Ej: Resuelve la siguiente operación')),
                ('question_text', models.CharField(help_text='Ej: 5 + 2 = ? o ¿Cuál es el doble de 4?', max_length=255)),
                ('correct_answer', models.CharField(help_text='Respuesta esperada. Ej: 7 o 8', max_length=50)),
                ('answer_type', models.CharField(choices=[('input', 'Campo de texto'), ('multiple_choice', 'Opción múltiple'), ('visual', 'Juego visual')], default='input', help_text='Tipo de interacción esperada', max_length=20)),
                ('options', models.JSONField(blank=True, help_text="Solo para opción múltiple. Ej: ['6','7','8','9']", null=True)),
                ('feedback', models.TextField(blank=True, help_text='Explicación que se muestra después de responder. Ej: Porque 5 + 2 = 7')),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('fácil', 'Fácil'), ('media', 'Media'), ('difícil', 'Difícil')], default='fácil', max_length=20)),
                ('xp_value', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_lessons', to='courses.course')),
            ],
        ),
    ]
