# Generated by Django 4.2.20 on 2025-07-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathLesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=50)),
                ('answer_type', models.CharField(choices=[('input', 'Campo de texto'), ('multiple_choice', 'Opcion multiple')], default='input', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Solo para opcion multiple', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mathLesson.mathlesson')),
            ],
        ),
    ]
