# Generated by Django 4.2.20 on 2025-07-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathLesson', '0002_mathexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathlesson',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='mathlesson',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='mathlesson',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mathlesson',
            name='options',
        ),
        migrations.RemoveField(
            model_name='mathlesson',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='mathexercise',
            name='answer_type',
            field=models.CharField(choices=[('input', 'Campo de texto'), ('multiple_choice', 'Opción múltiple')], default='input', max_length=20),
        ),
        migrations.AlterField(
            model_name='mathexercise',
            name='options',
            field=models.JSONField(blank=True, help_text='Solo para opción múltiple', null=True),
        ),
    ]
