# Generated by Django 4.2.20 on 2025-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathLesson', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='accuracy',
            field=models.FloatField(default=0.0, help_text='Porcentaje de respuestas correctas'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='retries',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de intentos realizados'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Fecha de finalización', null=True),
        ),
    ]
